server:
  port: 8888
spring:
  application:
    name: pay-config-server
  cloud:
    ##配置中心
    config:
      server:
        git:
          # uri: https://xx.com/foo/pay-config.git
          # username: xxx@cc.com
          # password: xxxxxxx
eureka:
  client:
    service-url:
      defaultZone: http://pay-eureka-server:8761/eureka
  instance:
    hostname: pay-config-server
#management:
#  endpoints:
#    web:
#      exposure:
#        exclude: "*"
