server:
  port: 8888
spring:
  application:
    name: pay-config-server
  cloud:
    ##配置中心
    config:
      server:
        git:
          uri: https://gitee.com/chenwee/pay-config.git
          username: cw961590280@hotmail.com
          password: cw438171439
eureka:
  client:
    service-url:
      defaultZone: http://pay-eureka-server:8761/eureka
management:
  endpoints:
    web:
      exposure:
        exclude: "*"
